<a href="https://colab.research.google.com/github/iyersamridhi/NewsScraping/blob/main/copy_of_BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow_text 
!pip install tensorflow_hub

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.8 MB 6.1 MB/s 
     |████████████████████████████████| 588.3 MB 20 kB/s 
     |████████████████████████████████| 6.0 MB 62.7 MB/s 
     |████████████████████████████████| 439 kB 76.0 MB/s 
     |████████████████████████████████| 1.7 MB 70.8 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.9.0
    Uninstalling tensorflow-estimator-2.9.0:
      Successfully uninstalled tensorflow-estimator-2.9.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.9.1
    Uninstalling tensorboard-2.9.1:
      Successfully uninstalled tensorboard-2.9.1
  Attempting uninstall: keras
    Found existing installation: keras 2.9.0
    Uninstalling keras-2.9.0:
      Successfully uninstalled keras-2.9.0
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 1.1

In [ ]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

In [ ]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [ ]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [ ]:
text_test = ['nice movie indeed','I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_word_ids', 'input_mask', 'input_type_ids'])

In [ ]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [ ]:
#importing our final scraped dataset

import pandas as pd

df = pd.read_csv('final_data.csv')

In [ ]:
#df.head()
#df.head(20)
print(df.iloc[2])


Unnamed: 0                                                      2
Unnamed: 0.1                                                  2.0
title           A God of War TV show is officially coming to A...
description     Amazon’s rumored God of War Prime Video show h...
url             https://www.theverge.com/2022/12/14/23509418/g...
index                                                           2
Name: 2, dtype: object


In [ ]:
a = df['title']
a = a.to_list()

In [ ]:
text_preprocessed = bert_preprocess_model(a)

In [ ]:
bert_model = hub.KerasLayer(encoder_url)

In [ ]:
bert_results = bert_model(text_preprocessed)

In [ ]:
import seaborn as sns
from sklearn.metrics import pairwise
def plot_similarity(features, labels):
  """Plot a similarity matrix of the embeddings."""
  cos_sim = pairwise.cosine_similarity(features)
  sns.set(font_scale=1.2)
  cbar_kws=dict(use_gridspec=False, location="left")
  g = sns.heatmap(
      cos_sim, xticklabels=labels, yticklabels=labels,
      vmin=0, vmax=1, cmap="Blues", cbar_kws=cbar_kws)
  g.tick_params(labelright=True, labelleft=False)
  g.set_yticklabels(labels, rotation=0)
  g.set_title("Semantic Textual Similarity")


In [ ]:
cos_sim = pairwise.cosine_similarity(bert_results['pooled_output'])
len(cos_sim)
print(type(cos_sim))

<class 'numpy.ndarray'>


In [ ]:
cos_sim.shape

(1284, 1284)

In [ ]:
cos_sim

array([[1.0000002 , 0.9404485 , 0.9805989 , ..., 0.9414948 , 0.8054834 ,
        0.927897  ],
       [0.9404485 , 1.        , 0.9493502 , ..., 0.99546057, 0.629422  ,
        0.9855678 ],
       [0.9805989 , 0.9493502 , 1.        , ..., 0.948518  , 0.79784065,
        0.9391405 ],
       ...,
       [0.9414948 , 0.99546057, 0.948518  , ..., 0.99999976, 0.6283771 ,
        0.98286283],
       [0.8054834 , 0.629422  , 0.79784065, ..., 0.6283771 , 0.99999976,
        0.65380824],
       [0.927897  , 0.9855678 , 0.9391405 , ..., 0.98286283, 0.65380824,
        0.99999994]], dtype=float32)

In [ ]:
import pandas as pd
import numpy as np
similarity_df = pd.DataFrame() 
similarity_df = pd.DataFrame(cos_sim)
#print(similarity_df)
#print(type(similarity_df))
# set multi-index
similarity_df['index'] = np.arange(similarity_df.shape[0])
similarity_df
#similarity_df[similarity_df["0"] ==  0.85


0       0.981493
1       0.958959
2       0.975151
3       0.951359
4       0.808141
          ...   
1279    0.976451
1280    0.976649
1281    0.953347
1282    0.784351
1283    0.948341
Name: 9, Length: 1284, dtype: float32

In [ ]:
dicts = {}
keys = range(300)
for i in range(300):
  #threshold_df = similarity_df[similarity_df[i] > 0.92]
  #threshold_df = similarity_df[similarity_df[i] > 0.85 & similarity_df[i] <0.93]
  threshold_df = similarity_df[similarity_df[i].between(0.85, 0.92)]

  #threshold_df= similarity_df[(similarity_df[similarity_df[i] > 0.85]) & (similarity_df[i] < 0.93)]

  for i in keys:
        dicts[i] =  threshold_list = threshold_df['index'].tolist()
print(dicts)
print(len(dicts[0]))
#for key,values in dicts.items():
     #for v in values:
          #print(key," : ",v)

  








{0: [1, 3, 4, 5, 6, 8, 11, 12, 14, 15, 16, 17, 22, 23, 25, 28, 31, 33, 34, 37, 40, 41, 43, 45, 48, 55, 56, 61, 62, 64, 71, 73, 77, 78, 83, 84, 85, 87, 90, 96, 100, 102, 103, 104, 105, 109, 110, 111, 112, 119, 121, 125, 127, 128, 133, 134, 137, 140, 142, 145, 146, 151, 153, 155, 163, 164, 166, 169, 172, 173, 180, 185, 188, 196, 210, 215, 216, 218, 222, 229, 230, 231, 236, 251, 252, 256, 269, 274, 288, 293, 294, 298, 303, 305, 314, 326, 329, 345, 348, 349, 352, 355, 358, 365, 366, 370, 371, 372, 376, 386, 395, 397, 400, 402, 403, 404, 405, 407, 409, 411, 412, 422, 426, 427, 429, 436, 439, 441, 445, 447, 448, 449, 453, 457, 461, 462, 463, 466, 469, 470, 473, 477, 479, 480, 485, 489, 491, 492, 497, 498, 499, 502, 507, 521, 522, 523, 525, 526, 529, 537, 540, 542, 551, 552, 565, 569, 573, 579, 582, 587, 588, 589, 590, 591, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 609, 612, 614, 616, 618, 620, 624, 625, 628, 632, 636, 642, 644, 646, 647, 656, 670, 675, 682, 694, 698, 702, 7

In [ ]:
for i in range(len(user_1)):
  post_id=user_1[i]
  #dicts[post_id]
  dicts[post_id] = threshold_list 1 
  #print(threshold_list)
  for j in range(len(threshold_list)):
    #print(len(threshold_list))
    #threshold_item = threshold_list[j]
    print(df.iloc[threshold_list[j]])
    

    








Unnamed: 0                                                      1
Unnamed: 0.1                                                  1.0
title               Ukraine war: Odesa and Melitopol under attack
description     Russian drone attacks leave 1.5 million Ukrain...
url              https://www.bbc.co.uk/news/world-europe-63933132
index                                                           1
Name: 1, dtype: object
Unnamed: 0                                                      3
Unnamed: 0.1                                                  3.0
title                   Ukraine war: Moldova braces for blackouts
description     Residents say they are already struggling to c...
url              https://www.bbc.co.uk/news/world-europe-63792499
index                                                           3
Name: 3, dtype: object
Unnamed: 0                                                      4
Unnamed: 0.1                                                  4.0
title           Elon Musk is d

In [ ]:
myDict = dict()
  
# Creating a list
myDict = dict()
  
# Creating a list
valList = ['1', '2', '3']
  
# Iterating the elements in list
for val in valList:
    for ele in range(int(val), int(val) + 2): 
        myDict.setdefault(ele, []).append(val)
  
print(myDict)

  
# Iterating the elements in list
for val in valList:
    for ele in range(int(val), int(val) + 2): 
        myDict.setdefault(ele, []).append(val)
  
print(myDict)
